### ISSUE TITLE
Finance issue

### ISSUE THREAD

**Issue by bakerzone** [Aries007691/qb-vehicleshop#1]
Hiya. wonderful script ... one issue though, if the main PDM / or luxury is set to managed with the job, and the employee tries to offer finance to a civilian,  even if there is stock, the check stock event shows that there is no stock, even if there is:

Any ideas?

-- Finance vehicle to customer
RegisterNetEvent('qb-vehicleshop:server:sellfinanceVehicle', function(downPayment, paymentAmount, vehicle, playerid, stock)
    local src = source
    local player = QBCore.Functions.GetPlayer(src)
    local stock = tonumber(stock)
    if stock == nil or stock < 1 then
        TriggerClientEvent('QBCore:Notify', src, 'Out of stock', 'error')
        return
    end
    local target = QBCore.Functions.GetPlayer(tonumber(playerid))

**Comment by YetiDev1123** [comment]
hello bakerzone can you explain to me how to get vehicles stock to the cardealer ?

**Comment by BranTheOtter** [comment]
I am unsure if you have this issue still but I had this issue but I fixed it;

on the Client.lua - Line 821
`TriggerServerEvent('qb-vehicleshop:server:sellfinanceVehicle', dialog.downPayment, dialog.paymentAmount, data.vehicle, dialog.playerid)
`

The stock was forgoten to be added to this (add `data.stock` to the ending);
`TriggerServerEvent('qb-vehicleshop:server:sellfinanceVehicle', dialog.downPayment, dialog.paymentAmount, data.vehicle, dialog.playerid, data.stock)
`
