### ISSUE TITLE
Sell vehicle issue!

### ISSUE THREAD

**Issue by impossiblt24** [Aries007691/qb-vehicleshop#3]
![1](https://github.com/Aries007691/qb-vehicleshop/assets/113254479/8ec1fde9-45b0-45c1-b9fd-6e0426dc6b8e)
![2](https://github.com/Aries007691/qb-vehicleshop/assets/113254479/b3819d26-e77d-403d-9e11-93704f69b916)
I had 3 stock of vehicle but when i sold it to my self it show "Out of stock" can you guys help me with this

**Comment by impossiblt24** [comment]
i use the latest of this script

**Comment by IlMicioLetale** [comment]
how you fix? thank you

**Comment by impossiblt24** [comment]
> how you fix? thank you

find this line:
RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid)

then just add stock at the end of this line:
RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid, stock)

like this

**Comment by IlMicioLetale** [comment]
> > how you fix? thank you
> 
> find this line in server.lua: RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid)
> 
> then just add stock at the end of this line: RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid, stock)
> 
> like this

Thank you so much man!!
