### ISSUE TITLE
Empty stock

### ISSUE THREAD

**Issue by IlMicioLetale** [Aries007691/qb-vehicleshop#4]
Hello, when I try to purchase a vehicle with a job (for example, I have the job car dealer and I'm buying a vehicle at the car dealer), it says there are not enough vehicles in stock, but that's not true. If I set it to "free-use," it allows me to purchase it.

**Comment by impossiblt24** [comment]
find this line in server.lua:
RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid)

then just add stock at the end of this line:
RegisterNetEvent('qb-vehicleshop:server:sellShowroomVehicle', function(data, playerid, stock)

like this

**Comment by IlMicioLetale** [comment]
Thank you so much, now work!!
