### ISSUE TITLE
stock issue 

### ISSUE THREAD

**Issue by Kilo-k** [Aries007691/qb-vehicleshop#5]
<img width="560" alt="Screenshot 2024-02-28 131747" src="https://github.com/Aries007691/qb-vehicleshop/assets/161592150/01f802ab-97a0-40e1-842d-cb5d221f662c">

even after adding stock it still says out of stock when trying to sell to player

**Comment by impossiblt24** [comment]
Did you import stock.sql and run the command /setstock

**Comment by Kilo-k** [comment]
yes

**Comment by impossiblt24** [comment]
I think that you forgot to add in client.lua too

**Comment by Kilo-k** [comment]
> I think that you forgot to add in client.lua too

thanks
